### ISSUE TITLE
Define output folder

### ISSUE THREAD

**Issue by nukeador** [mozilla/sumo-mt#4]
Ideally we should be able to define an output folder to avoid messing up with the source folder if we run the translation for other language later.

**Comment by soccerjustinh1** [comment]
I have an implementation of this on my local branch but I did not want to generate a pull request until I get a reply to the existing pull request for issue #6 

For this enhancement you just specify a output directory on the command line inputs and then if this directory (can be a relative directory) does not already exist then it is created. All the output files are dumped into here. If you have multiple levels of directories that are not already created then they are created for you (including parent directories).
