### ISSUE TITLE
Wrong code replacements

### ISSUE THREAD

**Issue by nukeador** [mozilla/sumo-mt#6]
''HTTP'' is recognized as a code but never replaced back, so we get numbers in the translated version. ''HTTP'' should not be a code to replace.

Also I've seen that in {key Ctrl} is translated and it shouldn't.

**Comment by soccerjustinh1** [comment]
Similarly there is also the directive of {filepath my file path} that is translated and this should not be translated.

**Comment by nukeador** [comment]
This seems to be solved now, thanks!
